import { Router, type IRouter } from "express";
import { db, productsTable } from "@workspace/db";

const router: IRouter = Router();

const COLORS = ["Black", "White", "Grey", "Navy", "Maroon", "Olive", "Royal Blue", "Red", "Forest Green", "Burgundy"];
const APPAREL_SIZES = ["XS", "S", "M", "L", "XL", "2XL", "3XL"];
const HAT_SIZES = ["One Size", "S/M", "L/XL"];
const GLOVE_SIZES = ["S", "M", "L", "XL"];
const SHOE_SIZES = ["6", "7", "8", "9", "10", "11", "12"];

const IMAGE = {
  streetwear: "https://images.unsplash.com/photo-1523381294911-8d3cead13475?w=800&auto=format&fit=crop",
  hoodie: "https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=800&auto=format&fit=crop",
  jacket: "https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?w=800&auto=format&fit=crop",
  fitness: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&auto=format&fit=crop",
  sports: "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=800&auto=format&fit=crop",
  boxing: "https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?w=800&auto=format&fit=crop",
  motocross: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&auto=format&fit=crop",
  caps: "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=800&auto=format&fit=crop",
  polo: "https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=800&auto=format&fit=crop",
  uniform: "https://images.unsplash.com/photo-1624526267942-ab0ff8a3e972?w=800&auto=format&fit=crop",
  ball: "https://images.unsplash.com/photo-1518091043644-c1d4457512c6?w=800&auto=format&fit=crop",
};

const PRODUCTS = [
  // ─── STREETWEAR ───────────────────────────────────────────────
  {
    name: "Track Suit", category: "Streetwear", subcategory: "Track Suits",
    description: "Premium quality track suits manufactured with moisture-wicking polyester blends, featuring ergonomic cuts for both athletic performance and casual streetwear. Available in full-zip tops and matching tapered trousers with elastic waistbands.",
    basePricePkr: 3200, availableSizes: APPAREL_SIZES, isCustomizable: true, featured: true,
    availableColors: COLORS, availableFabrics: ["100% Polyester", "Poly-Cotton Blend", "Tech Fleece"],
    availableGsm: [200, 260, 300], minOrderQty: 25,
    imageUrl: IMAGE.streetwear,
  },
  {
    name: "Fashion Jacket", category: "Streetwear", subcategory: "Fashion Jackets",
    description: "Contemporary fashion jackets crafted with premium woven fabrics and precision cut-and-sew construction, ideal for streetwear brands seeking a bold, modern silhouette. Fully customizable with embroidery, screen print, and DTF options.",
    basePricePkr: 4500, availableSizes: APPAREL_SIZES, isCustomizable: true, featured: false,
    availableColors: COLORS, availableFabrics: ["Oxford Nylon", "Ripstop Polyester", "Waxed Cotton"],
    availableGsm: [200, 240], minOrderQty: 25,
    imageUrl: IMAGE.jacket,
  },
  {
    name: "T-Shirt (Regular Fit)", category: "Streetwear", subcategory: "T-Shirts",
    description: "Classic regular-fit tees manufactured from ring-spun cotton with reinforced stitching at all stress points, providing exceptional durability and comfort for daily wear. Available in 180gsm and 220gsm weights to suit your brand standards.",
    basePricePkr: 1800, availableSizes: APPAREL_SIZES, isCustomizable: true, featured: true,
    availableColors: COLORS, availableFabrics: ["100% Cotton", "Cotton-Poly Blend"],
    availableGsm: [180, 200, 220], minOrderQty: 25,
    imageUrl: IMAGE.streetwear,
  },
  {
    name: "T-Shirt (Oversized)", category: "Streetwear", subcategory: "T-Shirts",
    description: "Drop-shoulder oversized tees with extended back length and wider sleeves, crafted from heavyweight 240gsm+ cotton for that premium streetwear feel. Ideal for custom printing due to the large flat canvas area.",
    basePricePkr: 2200, availableSizes: APPAREL_SIZES, isCustomizable: true, featured: true,
    availableColors: COLORS, availableFabrics: ["100% Cotton", "Heavy Cotton"],
    availableGsm: [220, 240, 280], minOrderQty: 25,
    imageUrl: IMAGE.streetwear,
  },
  {
    name: "Hoodie (Regular Fit)", category: "Streetwear", subcategory: "Hoodies",
    description: "Premium fleece-lined hoodies with kangaroo pockets, ribbed cuffs, and adjustable drawstring — built to last season after season. Manufactured with 320gsm+ cotton fleece for maximum warmth and a luxurious hand feel.",
    basePricePkr: 2800, availableSizes: APPAREL_SIZES, isCustomizable: true, featured: true,
    availableColors: COLORS, availableFabrics: ["Cotton Fleece", "Poly Fleece", "French Terry"],
    availableGsm: [300, 320, 360], minOrderQty: 25,
    imageUrl: IMAGE.hoodie,
  },
  {
    name: "Hoodie (Oversized)", category: "Streetwear", subcategory: "Hoodies",
    description: "Boxy-cut oversized hoodies with dropped shoulders and extended lengths, designed for the premium streetwear market. Each garment features double-stitched seams and premium-weight fleece for exceptional durability.",
    basePricePkr: 3200, availableSizes: APPAREL_SIZES, isCustomizable: true, featured: false,
    availableColors: COLORS, availableFabrics: ["Heavy Cotton Fleece", "French Terry"],
    availableGsm: [340, 380, 420], minOrderQty: 25,
    imageUrl: IMAGE.hoodie,
  },
  {
    name: "Sweatshirt (Regular Fit)", category: "Streetwear", subcategory: "Sweatshirts",
    description: "Crew-neck sweatshirts constructed from premium brushed fleece with flatlock stitching and ribbed collar, cuffs and hem for a clean, polished look. Perfect for screen printing and embroidery applications.",
    basePricePkr: 2400, availableSizes: APPAREL_SIZES, isCustomizable: true, featured: false,
    availableColors: COLORS, availableFabrics: ["Cotton Fleece", "Poly Fleece"],
    availableGsm: [280, 300, 320], minOrderQty: 25,
    imageUrl: IMAGE.hoodie,
  },
  {
    name: "Sweatshirt (Oversized)", category: "Streetwear", subcategory: "Sweatshirts",
    description: "Oversized crewneck sweatshirts with a relaxed boxy silhouette and heavyweight construction ideal for bold graphic prints. Our precision cut-and-sew process ensures consistent sizing across bulk orders.",
    basePricePkr: 2800, availableSizes: APPAREL_SIZES, isCustomizable: true, featured: false,
    availableColors: COLORS, availableFabrics: ["Heavy Cotton Fleece", "Tri-Blend Fleece"],
    availableGsm: [320, 360, 400], minOrderQty: 25,
    imageUrl: IMAGE.hoodie,
  },
  {
    name: "Beanie Hat", category: "Streetwear", subcategory: "Beanie Hats",
    description: "Ribbed knit beanies manufactured from acrylic-wool blend yarns providing excellent stretch recovery and insulation. Available with or without cuff fold, and with custom woven labels or embroidered logos.",
    basePricePkr: 800, availableSizes: HAT_SIZES, isCustomizable: true, featured: false,
    availableColors: COLORS, availableFabrics: ["Acrylic Knit", "Wool Blend"],
    availableGsm: [], minOrderQty: 25,
    imageUrl: IMAGE.caps,
  },
  {
    name: "Baseball Hat", category: "Streetwear", subcategory: "Baseball Hats",
    description: "Six-panel structured baseball hats built on a premium buckram-backed front panel with cotton-twill construction for embroidery durability. Features adjustable snapback or fitted options with your custom branding.",
    basePricePkr: 1200, availableSizes: HAT_SIZES, isCustomizable: true, featured: false,
    availableColors: COLORS, availableFabrics: ["Cotton Twill", "Polyester Mesh"],
    availableGsm: [], minOrderQty: 25,
    imageUrl: IMAGE.caps,
  },
  {
    name: "Trousers / Joggers", category: "Streetwear", subcategory: "Trousers",
    description: "Tapered jogger-style trousers with elastic waistbands, drawstring closure, and deep side pockets — manufactured from premium French terry or woven fabrics. Ribbed cuff ankles create a clean, athletic silhouette.",
    basePricePkr: 2200, availableSizes: APPAREL_SIZES, isCustomizable: true, featured: false,
    availableColors: COLORS, availableFabrics: ["French Terry", "Cotton Fleece", "Woven Nylon"],
    availableGsm: [260, 300, 320], minOrderQty: 25,
    imageUrl: IMAGE.streetwear,
  },
  {
    name: "Varsity / Letterman Jacket", category: "Streetwear", subcategory: "Varsity Jackets",
    description: "Authentic varsity letterman jackets with wool body, leather sleeves, and snap-button front closure — a signature product from Sialkot's finest manufacturers. Custom chenille patches, embroidery, and lining prints available.",
    basePricePkr: 6500, availableSizes: APPAREL_SIZES, isCustomizable: true, featured: true,
    availableColors: ["Black/White", "Navy/White", "Maroon/White", "Green/White", "Black/Gold", "Custom"],
    availableFabrics: ["Wool Body / Leather Sleeves", "Melton Wool", "Varsity Knit"],
    availableGsm: [], minOrderQty: 25,
    imageUrl: IMAGE.jacket,
  },
  {
    name: "Polo Shirt", category: "Streetwear", subcategory: "Polo Shirts",
    description: "Premium pique polo shirts manufactured with two-button placket, ribbed collar, and side vents for a classic athletic look suited to both sports and corporate markets. Embroidery-ready construction for clean logo placement.",
    basePricePkr: 1900, availableSizes: APPAREL_SIZES, isCustomizable: true, featured: false,
    availableColors: COLORS, availableFabrics: ["Cotton Pique", "Polyester Pique", "Mercerized Cotton"],
    availableGsm: [200, 220, 240], minOrderQty: 25,
    imageUrl: IMAGE.polo,
  },
  {
    name: "Tank Top (Men's)", category: "Streetwear", subcategory: "Tank Tops",
    description: "Men's muscle-fit tank tops with deep armholes and curved hem, constructed from 200gsm cotton-polyester blend for excellent shape retention after repeated washing. Available in streetwear and athletic cuts.",
    basePricePkr: 1200, availableSizes: APPAREL_SIZES, isCustomizable: true, featured: false,
    availableColors: COLORS, availableFabrics: ["Cotton-Poly Blend", "100% Polyester"],
    availableGsm: [180, 200, 220], minOrderQty: 25,
    imageUrl: IMAGE.fitness,
  },
  {
    name: "Tank Top (Women's)", category: "Streetwear", subcategory: "Tank Tops",
    description: "Women's racerback and spaghetti-strap tank tops tailored with feminine cuts and flattering seam placements. Manufactured from soft moisture-wicking fabrics suitable for both casual wear and gym use.",
    basePricePkr: 1100, availableSizes: ["XS", "S", "M", "L", "XL", "2XL"], isCustomizable: true, featured: false,
    availableColors: COLORS, availableFabrics: ["Cotton-Poly Blend", "Modal", "Bamboo"],
    availableGsm: [160, 180, 200], minOrderQty: 25,
    imageUrl: IMAGE.fitness,
  },
  {
    name: "Quarter-Zip Pullover", category: "Streetwear", subcategory: "Quarter-Zips",
    description: "Premium quarter-zip pullovers with moisture-wicking microfleece lining and ergonomic thumb-loop cuffs, perfect for layering in training or casual streetwear settings. Custom embroidery on chest and sleeve available.",
    basePricePkr: 2800, availableSizes: APPAREL_SIZES, isCustomizable: true, featured: false,
    availableColors: COLORS, availableFabrics: ["Micro Fleece", "Polar Fleece", "Tech Fabric"],
    availableGsm: [240, 280, 320], minOrderQty: 25,
    imageUrl: IMAGE.jacket,
  },
  {
    name: "Windbreaker", category: "Streetwear", subcategory: "Windbreakers",
    description: "Lightweight windproof and water-resistant windbreakers manufactured from ripstop nylon with taped seams and mesh lining. Features packable hood, zip pockets, and fully customizable with sublimation or screen print.",
    basePricePkr: 3500, availableSizes: APPAREL_SIZES, isCustomizable: true, featured: false,
    availableColors: COLORS, availableFabrics: ["Ripstop Nylon", "Polyester Taffeta"],
    availableGsm: [70, 80, 100], minOrderQty: 25,
    imageUrl: IMAGE.jacket,
  },
  {
    name: "Softshell Jacket", category: "Streetwear", subcategory: "Softshell Jackets",
    description: "Technical softshell jackets combining a water-resistant outer shell with bonded fleece inner layer for warmth without bulk. Designed for active outdoor use with articulated patterning and stretch panels.",
    basePricePkr: 5500, availableSizes: APPAREL_SIZES, isCustomizable: true, featured: false,
    availableColors: COLORS, availableFabrics: ["Softshell Bonded", "3-Layer Tech Shell"],
    availableGsm: [300, 360], minOrderQty: 25,
    imageUrl: IMAGE.jacket,
  },

  // ─── FITNESS WEAR ─────────────────────────────────────────────
  {
    name: "Gym T-Shirt", category: "Fitness Wear", subcategory: "Gym T-Shirts",
    description: "High-performance gym tees engineered with moisture-wicking polyester and mesh ventilation panels for superior breathability during intense workouts. Anti-odor treatment and flat seam construction prevent chafing.",
    basePricePkr: 1600, availableSizes: APPAREL_SIZES, isCustomizable: true, featured: false,
    availableColors: COLORS, availableFabrics: ["100% Polyester", "Poly-Spandex Blend"],
    availableGsm: [140, 160, 180], minOrderQty: 25,
    imageUrl: IMAGE.fitness,
  },
  {
    name: "Rashguard", category: "Fitness Wear", subcategory: "Rashguards",
    description: "UPF 50+ rashguards manufactured from 4-way stretch nylon-spandex blend, providing full coverage and compression for BJJ, surfing, and water sports. Custom sublimation printing delivers photo-quality graphics that never fade.",
    basePricePkr: 2200, availableSizes: APPAREL_SIZES, isCustomizable: true, featured: true,
    availableColors: ["Custom Sublimation"], availableFabrics: ["Nylon-Spandex (88/12)", "Polyester-Spandex"],
    availableGsm: [180, 200], minOrderQty: 25,
    imageUrl: IMAGE.fitness,
  },
  {
    name: "Sports Bra", category: "Fitness Wear", subcategory: "Sports Bras",
    description: "Medium-to-high impact sports bras with racerback design, wide underbust band, and removable padding — crafted from moisture-wicking stretch fabric for optimal support during training. Minimal seam construction reduces friction.",
    basePricePkr: 1400, availableSizes: ["XS", "S", "M", "L", "XL", "2XL"], isCustomizable: true, featured: false,
    availableColors: COLORS, availableFabrics: ["Polyester-Spandex", "Nylon-Spandex"],
    availableGsm: [160, 180], minOrderQty: 25,
    imageUrl: IMAGE.fitness,
  },
  {
    name: "Sublimation Sports Bra", category: "Fitness Wear", subcategory: "Sublimation Bras",
    description: "Full-panel sublimation sports bras with all-over custom print capability, manufactured from premium stretch fabric with compression lining and internal support structure. Ideal for activewear brands needing bold, unique designs.",
    basePricePkr: 1800, availableSizes: ["XS", "S", "M", "L", "XL", "2XL"], isCustomizable: true, featured: false,
    availableColors: ["Custom Sublimation"], availableFabrics: ["Polyester-Spandex (80/20)"],
    availableGsm: [180], minOrderQty: 25,
    imageUrl: IMAGE.fitness,
  },
  {
    name: "Crop Top", category: "Fitness Wear", subcategory: "Crop Tops",
    description: "Versatile crop tops available in cut-and-sew woven and knit constructions, from form-fitting athletic styles to relaxed casual silhouettes. Wide range of fabric options from lightweight jerseys to heavyweight French terry.",
    basePricePkr: 1400, availableSizes: ["XS", "S", "M", "L", "XL", "2XL"], isCustomizable: true, featured: false,
    availableColors: COLORS, availableFabrics: ["Cotton Jersey", "Poly-Spandex", "Ribbed Cotton"],
    availableGsm: [160, 180, 220], minOrderQty: 25,
    imageUrl: IMAGE.fitness,
  },
  {
    name: "Men's Athletic Shorts", category: "Fitness Wear", subcategory: "Men's Shorts",
    description: "5-inch and 7-inch inseam athletic shorts with inner liner, deep side pockets, and elastic waistband with internal drawstring — optimized for performance in gym, running, and court sports.",
    basePricePkr: 1600, availableSizes: APPAREL_SIZES, isCustomizable: true, featured: false,
    availableColors: COLORS, availableFabrics: ["100% Polyester", "Poly-Spandex Blend", "Woven Nylon"],
    availableGsm: [120, 140, 160], minOrderQty: 25,
    imageUrl: IMAGE.fitness,
  },
  {
    name: "Women's Athletic Shorts", category: "Fitness Wear", subcategory: "Women's Shorts",
    description: "Women's high-waisted training shorts with compression liner, side pockets, and flattering tailored cut — manufactured from four-way stretch fabric with moisture-management properties for all-day comfort.",
    basePricePkr: 1500, availableSizes: ["XS", "S", "M", "L", "XL", "2XL"], isCustomizable: true, featured: false,
    availableColors: COLORS, availableFabrics: ["Polyester-Spandex", "Nylon-Spandex"],
    availableGsm: [140, 160], minOrderQty: 25,
    imageUrl: IMAGE.fitness,
  },
  {
    name: "Leggings", category: "Fitness Wear", subcategory: "Leggings",
    description: "Full-length and 7/8 compression leggings manufactured from 4-way stretch nylon-spandex blend with squat-proof construction and high-waist design. Available with sublimation printing for full-panel custom graphics.",
    basePricePkr: 2000, availableSizes: ["XS", "S", "M", "L", "XL", "2XL"], isCustomizable: true, featured: false,
    availableColors: COLORS.concat(["Custom Sublimation"]), availableFabrics: ["Nylon-Spandex (80/20)", "Polyester-Spandex"],
    availableGsm: [200, 220], minOrderQty: 25,
    imageUrl: IMAGE.fitness,
  },
  {
    name: "Fitness Tank Top", category: "Fitness Wear", subcategory: "Tank Tops",
    description: "Performance tank tops with deep cut armholes and moisture-wicking construction for unrestricted movement during training. Available in cut-and-sew open-back, racerback, and muscle-tank styles.",
    basePricePkr: 1200, availableSizes: APPAREL_SIZES, isCustomizable: true, featured: false,
    availableColors: COLORS, availableFabrics: ["100% Polyester", "Poly-Spandex"],
    availableGsm: [140, 160], minOrderQty: 25,
    imageUrl: IMAGE.fitness,
  },

  // ─── SPORTS UNIFORMS ──────────────────────────────────────────
  {
    name: "Soccer Uniform Set", category: "Sports Uniforms", subcategory: "Soccer Uniforms",
    description: "Complete soccer uniform sets including sublimated jersey, shorts, and optional socks — engineered with breathable polyester mesh and moisture-wicking technology for peak on-field performance. Full team customization available.",
    basePricePkr: 3500, availableSizes: APPAREL_SIZES, isCustomizable: true, featured: true,
    availableColors: ["Custom Sublimation"], availableFabrics: ["100% Polyester Mesh", "Recycled Polyester"],
    availableGsm: [120, 140, 160], minOrderQty: 25,
    imageUrl: IMAGE.sports,
  },
  {
    name: "American Football Uniform", category: "Sports Uniforms", subcategory: "American Football Uniforms",
    description: "Durable American football uniforms featuring reinforced stretch jerseys and padded pants with integrated hip and thigh protection zones. Manufactured to NFHS and collegiate standards with customizable numbering and lettering.",
    basePricePkr: 5500, availableSizes: APPAREL_SIZES, isCustomizable: true, featured: false,
    availableColors: ["Custom Sublimation"], availableFabrics: ["Stretch Mesh", "Tackle Twill"],
    availableGsm: [180, 200], minOrderQty: 25,
    imageUrl: IMAGE.sports,
  },
  {
    name: "Basketball Jersey", category: "Sports Uniforms", subcategory: "Basketball Uniforms",
    description: "Lightweight sublimated basketball jerseys with breathable mesh construction, reinforced stitching at numbers, and performance-fit patterning for unrestricted movement. Available as reversible double-sided jerseys.",
    basePricePkr: 2500, availableSizes: APPAREL_SIZES, isCustomizable: true, featured: false,
    availableColors: ["Custom Sublimation"], availableFabrics: ["Polyester Mesh", "Double Knit"],
    availableGsm: [130, 150], minOrderQty: 25,
    imageUrl: IMAGE.sports,
  },
  {
    name: "Basketball Shorts", category: "Sports Uniforms", subcategory: "Basketball Uniforms",
    description: "Knee-length basketball shorts with side pockets, elastic waistband, and full sublimation printing capability. Made from moisture-wicking double-knit polyester that maintains shape and colorfastness through hundreds of washes.",
    basePricePkr: 1800, availableSizes: APPAREL_SIZES, isCustomizable: true, featured: false,
    availableColors: ["Custom Sublimation"], availableFabrics: ["Double Knit Polyester"],
    availableGsm: [150, 170], minOrderQty: 25,
    imageUrl: IMAGE.sports,
  },
  {
    name: "Baseball Jersey", category: "Sports Uniforms", subcategory: "Baseball Uniforms",
    description: "Traditional baseball jerseys in button-up and full-sublimation styles, manufactured with stretch double knit fabric and twill or sublimated lettering. Available with authentic raglan or set-in sleeves.",
    basePricePkr: 2800, availableSizes: APPAREL_SIZES, isCustomizable: true, featured: false,
    availableColors: ["White", "Grey", "Custom Sublimation"], availableFabrics: ["Double Knit Polyester", "Pinstripe Cotton"],
    availableGsm: [160, 180], minOrderQty: 25,
    imageUrl: IMAGE.uniform,
  },
  {
    name: "Baseball Pants", category: "Sports Uniforms", subcategory: "Baseball Uniforms",
    description: "Full-length and knicker-style baseball pants manufactured from durable double-knit polyester with reinforced knee panels and elastic waistband. Features sewn-in belt loops and sliding pad channels.",
    basePricePkr: 2200, availableSizes: APPAREL_SIZES, isCustomizable: true, featured: false,
    availableColors: ["White", "Grey", "Black", "Navy"], availableFabrics: ["Double Knit Polyester"],
    availableGsm: [200, 220], minOrderQty: 25,
    imageUrl: IMAGE.uniform,
  },
  {
    name: "Rugby Uniform", category: "Sports Uniforms", subcategory: "Rugby Uniforms",
    description: "Heavy-duty rugby jerseys manufactured from 260gsm+ polyester with reinforced shoulder panels, strengthened collar, and anti-snag stitching designed to withstand the physical demands of the game.",
    basePricePkr: 3200, availableSizes: APPAREL_SIZES, isCustomizable: true, featured: false,
    availableColors: ["Custom Sublimation"], availableFabrics: ["Heavy Polyester", "Cotton-Polyester Blend"],
    availableGsm: [260, 280, 300], minOrderQty: 25,
    imageUrl: IMAGE.sports,
  },
  {
    name: "Ice Hockey Uniform", category: "Sports Uniforms", subcategory: "Ice Hockey Uniforms",
    description: "Professional ice hockey jerseys with double-layer reinforced shoulders, deep-cut armpits for stick handling, and fully customizable sublimation or tackle-twill numbering. Includes matching breezers/shorts.",
    basePricePkr: 4500, availableSizes: APPAREL_SIZES, isCustomizable: true, featured: false,
    availableColors: ["Custom Sublimation"], availableFabrics: ["Polyester Birdseye", "Mesh Combination"],
    availableGsm: [200, 220], minOrderQty: 25,
    imageUrl: IMAGE.sports,
  },

  // ─── SPORTS GOODS ─────────────────────────────────────────────
  {
    name: "Basketball", category: "Sports Goods", subcategory: "Basketballs",
    description: "Official size 7 basketballs manufactured from genuine leather or composite materials with hand-stitched channels and deep pebble texture for superior grip and ball control. Custom logo printing available.",
    basePricePkr: 2000, availableSizes: ["Size 5", "Size 6", "Size 7"], isCustomizable: false, featured: false,
    availableColors: ["Orange", "Black", "Custom"], availableFabrics: ["Full Grain Leather", "Composite Leather"],
    availableGsm: [], minOrderQty: 50,
    imageUrl: IMAGE.ball,
  },
  {
    name: "Tennis Ball", category: "Sports Goods", subcategory: "Tennis Balls",
    description: "Pressurized tennis balls manufactured with premium core rubber and high-grade melton felt exterior, meeting ITF standards for tournament play. Custom branding available on canister packaging.",
    basePricePkr: 500, availableSizes: ["Standard"], isCustomizable: false, featured: false,
    availableColors: ["Yellow", "White"], availableFabrics: ["Felt"],
    availableGsm: [], minOrderQty: 50,
    imageUrl: IMAGE.ball,
  },
  {
    name: "Soccer Ball", category: "Sports Goods", subcategory: "Soccer Balls",
    description: "FIFA-tested soccer balls with thermally bonded 32-panel construction and butyl bladder for optimal air retention. Hand-stitched and machine-stitched options available across training and match-grade specifications.",
    basePricePkr: 2500, availableSizes: ["Size 3", "Size 4", "Size 5"], isCustomizable: false, featured: false,
    availableColors: ["Black/White", "Custom"], availableFabrics: ["PU Cover", "PVC Cover"],
    availableGsm: [], minOrderQty: 50,
    imageUrl: IMAGE.ball,
  },
  {
    name: "Cricket Ball", category: "Sports Goods", subcategory: "Cricket Balls",
    description: "Hand-stitched four-piece cricket balls manufactured from premium cork core wrapped in natural leather, meeting international cricket board specifications. Available in red, white, and pink for different match conditions.",
    basePricePkr: 1800, availableSizes: ["156g", "142g"], isCustomizable: false, featured: false,
    availableColors: ["Red", "White", "Pink"], availableFabrics: ["Genuine Leather"],
    availableGsm: [], minOrderQty: 50,
    imageUrl: IMAGE.ball,
  },
  {
    name: "Rugby Ball", category: "Sports Goods", subcategory: "Rugby Balls",
    description: "Official size 5 rugby balls with embossed grip panels and premium PU cover, providing excellent handling in wet and dry conditions. Custom team branding and IRB-compliant specifications available.",
    basePricePkr: 2200, availableSizes: ["Size 3", "Size 4", "Size 5"], isCustomizable: false, featured: false,
    availableColors: ["Brown", "Black", "Custom"], availableFabrics: ["PU Cover", "Leather"],
    availableGsm: [], minOrderQty: 50,
    imageUrl: IMAGE.ball,
  },

  // ─── TEAM WEAR ────────────────────────────────────────────────
  {
    name: "School Uniform Set", category: "Team Wear", subcategory: "School Uniforms",
    description: "Complete school uniform solutions including shirts, trousers, skirts, blazers, and ties manufactured to institutional specifications with durable school-grade fabrics and reinforced stitching for longevity.",
    basePricePkr: 3000, availableSizes: APPAREL_SIZES, isCustomizable: true, featured: false,
    availableColors: COLORS, availableFabrics: ["Polyester-Viscose", "Cotton-Poly Blend", "Gabardine"],
    availableGsm: [200, 240, 280], minOrderQty: 50,
    imageUrl: IMAGE.uniform,
  },
  {
    name: "Team Rugby Kit", category: "Team Wear", subcategory: "Rugby Uniforms",
    description: "Complete team rugby kits with jerseys, shorts, and socks in matching team colors with sublimated or embroidered numbering. Built for repeated washing and the physical demands of competitive rugby.",
    basePricePkr: 4000, availableSizes: APPAREL_SIZES, isCustomizable: true, featured: false,
    availableColors: ["Custom Sublimation"], availableFabrics: ["Heavy Polyester"],
    availableGsm: [260, 280], minOrderQty: 25,
    imageUrl: IMAGE.sports,
  },
  {
    name: "Team Ice Hockey Kit", category: "Team Wear", subcategory: "Ice Hockey Uniforms",
    description: "Full team ice hockey kits including jerseys and matching socks with reinforced construction for on-ice performance. Custom sublimation printing enables unique team identity with photo-quality graphics.",
    basePricePkr: 5000, availableSizes: APPAREL_SIZES, isCustomizable: true, featured: false,
    availableColors: ["Custom Sublimation"], availableFabrics: ["Polyester Birdseye"],
    availableGsm: [200, 220], minOrderQty: 25,
    imageUrl: IMAGE.sports,
  },

  // ─── BOXING ───────────────────────────────────────────────────
  {
    name: "Boxing Shorts", category: "Boxing", subcategory: "Boxing Shorts",
    description: "Satin-finish boxing shorts with wide elastic waistband, side split panels for leg mobility, and full sublimation print capability for team and brand customization. Available in traditional and modern cuts.",
    basePricePkr: 1800, availableSizes: APPAREL_SIZES, isCustomizable: true, featured: true,
    availableColors: ["Custom Sublimation"], availableFabrics: ["Satin Polyester", "Stretch Satin"],
    availableGsm: [80, 100], minOrderQty: 25,
    imageUrl: IMAGE.boxing,
  },
  {
    name: "Boxing Gloves", category: "Boxing", subcategory: "Boxing Gloves",
    description: "Professional boxing gloves manufactured from genuine cowhide leather with multi-layer foam padding system and velcro wrist closure. Available in training, sparring, and competition weights from 8oz to 16oz.",
    basePricePkr: 3500, availableSizes: ["8oz", "10oz", "12oz", "14oz", "16oz"], isCustomizable: true, featured: false,
    availableColors: ["Black", "Red", "Blue", "White", "Custom"], availableFabrics: ["Genuine Leather", "Synthetic Leather"],
    availableGsm: [], minOrderQty: 25,
    imageUrl: IMAGE.boxing,
  },
  {
    name: "Boxing Shin Pads", category: "Boxing", subcategory: "Boxing Shin Pads",
    description: "Full-coverage shin guards with anatomically molded inner padding and breathable mesh backing, manufactured for Muay Thai and kickboxing training. Velcro closures ensure secure fit during intense sessions.",
    basePricePkr: 2500, availableSizes: ["S", "M", "L", "XL"], isCustomizable: true, featured: false,
    availableColors: ["Black", "Red", "Blue", "Custom"], availableFabrics: ["PU Leather", "Genuine Leather"],
    availableGsm: [], minOrderQty: 25,
    imageUrl: IMAGE.boxing,
  },
  {
    name: "Boxing Head Guard", category: "Boxing", subcategory: "Boxing Head Guards",
    description: "Competition and training head guards with full cheek and chin protection, manufactured from shock-absorbing foam with high-density outer shell. Open-face and cheek-bar designs available to international safety standards.",
    basePricePkr: 3000, availableSizes: ["S/M", "L/XL"], isCustomizable: true, featured: false,
    availableColors: ["Black", "Red", "Blue", "White", "Custom"], availableFabrics: ["PU Leather", "Genuine Leather"],
    availableGsm: [], minOrderQty: 25,
    imageUrl: IMAGE.boxing,
  },
  {
    name: "Boxing Chest Guard", category: "Boxing", subcategory: "Boxing Chest Guards",
    description: "Protective chest guards for boxing and martial arts, featuring contoured design with adjustable shoulder and side straps. High-density impact foam with outer shell manufactured for both male and female athletes.",
    basePricePkr: 3200, availableSizes: ["S", "M", "L", "XL"], isCustomizable: true, featured: false,
    availableColors: ["Black", "Red", "Blue", "Custom"], availableFabrics: ["PU Leather", "Genuine Leather"],
    availableGsm: [], minOrderQty: 25,
    imageUrl: IMAGE.boxing,
  },
  {
    name: "Thai Pads", category: "Boxing", subcategory: "Boxing Thai Pads",
    description: "Professional Muay Thai focus mitts and kicking pads manufactured from premium leather with multiple foam layers for optimal impact absorption. Ergonomic handle design reduces trainer hand and wrist fatigue.",
    basePricePkr: 4000, availableSizes: ["One Size"], isCustomizable: true, featured: false,
    availableColors: ["Black", "Red", "Blue", "Custom"], availableFabrics: ["Genuine Leather", "Synthetic Leather"],
    availableGsm: [], minOrderQty: 25,
    imageUrl: IMAGE.boxing,
  },
  {
    name: "Boxing Robe", category: "Boxing", subcategory: "Boxing Robes",
    description: "Satin boxing robes with hood, satin lining, and fully customizable with embroidery and sublimation printing for fighter names and team branding. Available in short and full-length styles.",
    basePricePkr: 2200, availableSizes: APPAREL_SIZES, isCustomizable: true, featured: false,
    availableColors: ["Custom Sublimation"], availableFabrics: ["Satin Polyester", "Heavy Satin"],
    availableGsm: [], minOrderQty: 25,
    imageUrl: IMAGE.boxing,
  },

  // ─── MOTOCROSS ────────────────────────────────────────────────
  {
    name: "Motocross Jersey Set", category: "Motocross", subcategory: "Motocross Sets",
    description: "Complete motocross kit including sublimated jersey, pants, and gloves manufactured to FIM competition standards with reinforced abrasion zones and CE-rated protective padding pockets.",
    basePricePkr: 8000, availableSizes: APPAREL_SIZES, isCustomizable: true, featured: true,
    availableColors: ["Custom Sublimation"], availableFabrics: ["100% Polyester", "Poly-Spandex Blend"],
    availableGsm: [160, 180], minOrderQty: 25,
    imageUrl: IMAGE.motocross,
  },
  {
    name: "Motocross Jersey", category: "Motocross", subcategory: "Jerseys",
    description: "Lightweight motocross jerseys with moisture-wicking properties, reinforced elbows, and full sublimation printing for team and sponsor logos. Built with stretch mesh panels at underarms for maximum ventilation.",
    basePricePkr: 3000, availableSizes: APPAREL_SIZES, isCustomizable: true, featured: false,
    availableColors: ["Custom Sublimation"], availableFabrics: ["Polyester Mesh", "Poly-Spandex"],
    availableGsm: [140, 160], minOrderQty: 25,
    imageUrl: IMAGE.motocross,
  },
  {
    name: "Motocross Pants", category: "Motocross", subcategory: "Pants",
    description: "Heavy-duty motocross pants with abrasion-resistant outer shell, articulated knee construction, and pre-curved seating area for riding ergonomics. Reinforced inner leg panels and multiple ventilation openings.",
    basePricePkr: 5500, availableSizes: APPAREL_SIZES, isCustomizable: true, featured: false,
    availableColors: ["Custom Sublimation"], availableFabrics: ["Cordura Nylon", "Poly-Spandex"],
    availableGsm: [200, 250], minOrderQty: 25,
    imageUrl: IMAGE.motocross,
  },
  {
    name: "Motocross Jacket", category: "Motocross", subcategory: "Jackets",
    description: "Technical motocross jackets with CE Level 1 elbow and shoulder armor, waterproof outer shell, and full sublimation graphics capability. Features ventilation zips and adjustable cuffs, hem, and collar.",
    basePricePkr: 9000, availableSizes: APPAREL_SIZES, isCustomizable: true, featured: false,
    availableColors: ["Custom Sublimation"], availableFabrics: ["Cordura 600D", "TPU Membrane"],
    availableGsm: [], minOrderQty: 25,
    imageUrl: IMAGE.motocross,
  },
  {
    name: "Motocross Gloves", category: "Motocross", subcategory: "Gloves",
    description: "Off-road motorcycle gloves with pre-curved palm, knuckle protectors, and silicone grip printing — manufactured from abrasion-resistant synthetic leather and breathable stretch panels.",
    basePricePkr: 2000, availableSizes: GLOVE_SIZES, isCustomizable: true, featured: false,
    availableColors: ["Black", "Black/Red", "Black/Blue", "Custom"], availableFabrics: ["Synthetic Leather", "Genuine Leather"],
    availableGsm: [], minOrderQty: 25,
    imageUrl: IMAGE.motocross,
  },
  {
    name: "Body Armour Vest", category: "Motocross", subcategory: "Body Armour",
    description: "CE Level 1 rated body armour vests with integrated back, chest, and side protection panels — designed for motocross, mountain biking, and extreme sports. Lightweight EVA foam construction with moisture-wicking inner liner.",
    basePricePkr: 6500, availableSizes: APPAREL_SIZES, isCustomizable: false, featured: false,
    availableColors: ["Black", "Black/Orange", "Black/Blue"], availableFabrics: ["EVA Foam / Mesh"],
    availableGsm: [], minOrderQty: 25,
    imageUrl: IMAGE.motocross,
  },
  {
    name: "Motocross Knee Pads", category: "Motocross", subcategory: "Knee Pads",
    description: "Professional motocross knee guards with hard outer shell and dual-density foam inner padding, designed for under-pants or over-pants use. Wrap-around strap system with ratchet buckle for secure hold.",
    basePricePkr: 3500, availableSizes: ["S/M", "L/XL"], isCustomizable: false, featured: false,
    availableColors: ["Black", "Black/Orange"], availableFabrics: ["ABS Plastic / EVA Foam"],
    availableGsm: [], minOrderQty: 25,
    imageUrl: IMAGE.motocross,
  },

  // ─── CAPS ─────────────────────────────────────────────────────
  {
    name: "Trucker Hat", category: "Caps", subcategory: "Trucker Hats",
    description: "Five-panel trucker caps with structured foam front panel and breathable mesh back, available with snapback or strapback closure. Front panel optimized for embroidery and patch applications.",
    basePricePkr: 1100, availableSizes: HAT_SIZES, isCustomizable: true, featured: false,
    availableColors: COLORS, availableFabrics: ["Cotton Twill / Mesh", "Polyester Twill / Mesh"],
    availableGsm: [], minOrderQty: 25,
    imageUrl: IMAGE.caps,
  },
  {
    name: "Baseball Cap", category: "Caps", subcategory: "Baseball Caps",
    description: "Classic six-panel baseball caps with structured and unstructured options, buckram-backed front panels for embroidery, and premium sweatband lining. Available in snapback, fitted, and flexfit sizing systems.",
    basePricePkr: 1200, availableSizes: HAT_SIZES, isCustomizable: true, featured: false,
    availableColors: COLORS, availableFabrics: ["Cotton Twill", "Polyester", "Wool Blend"],
    availableGsm: [], minOrderQty: 25,
    imageUrl: IMAGE.caps,
  },
  {
    name: "Bucket Hat", category: "Caps", subcategory: "Bucket Hats",
    description: "Reversible and single-layer bucket hats manufactured from premium cotton canvas or nylon with all-round brim and interior hat band. Full sublimation printing and embroidery available.",
    basePricePkr: 1400, availableSizes: HAT_SIZES, isCustomizable: true, featured: false,
    availableColors: COLORS, availableFabrics: ["Cotton Canvas", "Nylon", "Denim"],
    availableGsm: [], minOrderQty: 25,
    imageUrl: IMAGE.caps,
  },
  {
    name: "Beanie / Knit Cap", category: "Caps", subcategory: "Beanie Hats",
    description: "Premium knit beanies in cuffed and slouchy styles manufactured from acrylic-wool blends for warmth and colorfastness. Custom woven patch labels and embroidered logos positioned to standard placements.",
    basePricePkr: 900, availableSizes: HAT_SIZES, isCustomizable: true, featured: false,
    availableColors: COLORS, availableFabrics: ["Acrylic Knit", "Wool Blend", "Merino Wool"],
    availableGsm: [], minOrderQty: 25,
    imageUrl: IMAGE.caps,
  },
];

router.post("/seed-products", async (_req, res): Promise<void> => {
  try {
    await db.delete(productsTable);

    const toInsert = PRODUCTS.map(p => ({
      name: p.name,
      category: p.category,
      subcategory: p.subcategory,
      description: p.description,
      basePrice: Math.round((p.basePricePkr / 280) * 100) / 100,
      basePricePkr: p.basePricePkr,
      availableColors: p.availableColors,
      availableSizes: p.availableSizes,
      availableFabrics: p.availableFabrics,
      availableGsm: p.availableGsm,
      minOrderQty: p.minOrderQty,
      isCustomizable: p.isCustomizable,
      imageUrl: p.imageUrl,
      featured: p.featured,
    }));

    const inserted = await db.insert(productsTable).values(toInsert).returning();
    res.json({ success: true, count: inserted.length, message: `Seeded ${inserted.length} products successfully.` });
  } catch (err) {
    console.error("Seed error:", err);
    res.status(500).json({ error: String(err) });
  }
});

export default router;
